### ISSUE TITLE
Can't build on Varnish 4

### ISSUE THREAD

**Issue by blindpet** [Dridi/libvmod-querystring#16]
I am getting No Varnish source tree specified. I am able to build other vmods like vsthrottle and vshield. Does libvmod-query string not take advantage of the libvarnishapi-dev

**Comment by Dridi** [comment]
It doesn't because the build system currently supports both Varnish 3 and 4. Once Varnish 4.1 is out I will add support for it and drop Varnish 3 compatibility. I also intend to change the API and the way the VMOD is used to take advantage of 4.0+ features.

I will keep this issue open and let you know when the next tag is available.

**Comment by blindpet** [comment]
Other vmods have a separate branch for 4 and 4.1 compatibility. Despite 3.0 being EOL it is still used by people reliant on certain vmods that haven't been ported yet.

Looking forward to 4.1 release

**Comment by Dridi** [comment]
I know, but I didn't want to maintain several branches, and 3.0 prevents me from using 4+ features. And I suppose I'm too much of a Fedora person, I tend to disregard EOL software :)

**Comment by blindpet** [comment]
I think it's fair enough if you create a new branch and then just abandon the old one, no need to maintain it as people can always fork it if necessary. I am still using Varnish 3 just because it serves my needs but am planning to move to 4.1 when php7 is out and all that.

Removing query strings without having to use a plugin will just be the icing on the cake :)

**Comment by gauthier-delacroix** [comment]
Hi,

Do you still plan to update the build process to 4.0+ ?

**Comment by Dridi** [comment]
Good timing, I did it on Thursday in a long airport/plane day :)

I still have to update the documentation and I also started a cleanup of the code base but expect an update within a week.

**Comment by Dridi** [comment]
@gauthier-delacroix I have pushed changes allowing a proper build for Varnish 4+ and dropped support for 3.0 altogether. I also updated the README now that I don't use it as the VMOD's manual for 3.0 builds.

I want to do more cleanup before I cut a 0.4 release but I have no intentions of breaking the ABI.

**Comment by Dridi** [comment]
Closing, feel free to reopen this issue if the build is not working as expected for a Varnish 4.x module.

**Comment by quintonparker** [comment]
hi

trying to compile for varnish 4.1.1 on ubuntu lts precise

`make` is barfing with error message

vmod_querystring.c:44:20: fatal error: vcc_if.h: No such file or directory
compilation terminated.
make[2]: *** [vmod_querystring.lo] Error 1
make[2]: Leaving directory `/home/quinton/libvmod-querystring/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/quinton/libvmod-querystring'
make: *** [all] Error 2

Help?

**Comment by quintonparker** [comment]
or should i rather post a new issue?

**Comment by Dridi** [comment]
@quintonparker Could you please file a new issue and describe the steps that lead to this error message?

**Comment by quintonparker** [comment]
@Dridi sure. thanks. https://github.com/Dridi/libvmod-querystring/issues/21
