### ISSUE TITLE
make install fails after disabling man file generation with ./configure --with-rst2man=true

### ISSUE THREAD

**Issue by dbeckham** [Dridi/libvmod-querystring#24]
After running configure with `./configure --with-rst2man=true` to disable man file generation, `make install` still expects the man pages, and will fail. 

This is a production image and no man pages are needed, nor do I need python-docutils and all of its dependencies installed for anything else.

If rst2man is missing when compiling official vmods like those at https://github.com/varnish/varnish-modules, the configure script will recognize that and not bother trying to generate, or install the man files.

`make install` error output:

```
# ./configure --with-rst2man=true
...
# make
...
# make install
Making install in src
make[1]: Entering directory `/tmp/libvmod-querystring-0.5/src'
true vmod_querystring.man.rst vmod_querystring.3
make[2]: Entering directory `/tmp/libvmod-querystring-0.5/src'
make[2]: Nothing to be done for `install-exec-am'.
true vmod_querystring.man.rst vmod_querystring.3
 /bin/mkdir -p '/usr/share/man/man3'
 /usr/bin/install -c -m 644 ./vmod_querystring.3 '/usr/share/man/man3'
/usr/bin/install: cannot stat './vmod_querystring.3': No such file or directory
make[2]: *** [install-man3] Error 1
make[2]: Leaving directory `/tmp/libvmod-querystring-0.5/src'
make[1]: *** [install-am] Error 2
make[1]: Leaving directory `/tmp/libvmod-querystring-0.5/src'
make: *** [install-recursive] Error 1
```

**Comment by Dridi** [comment]
Hi @dbeckham,

I have a mixed opinions on this issues, but more importantly I have a [feature/build](https://github.com/Dridi/libvmod-querystring/blob/feature/build) branch where I made heavy changes on the build system. Could you try building this one instead?

Please note that it is based on the [feature/obj](https://github.com/Dridi/libvmod-querystring/tree/feature/obj) branch that will *very soon* take over the master branch. If you are using modules from varnish/modules, it also means that you are running Varnish 4.1.2 so you should be fine with this branch. More information on the changes in #23, feel free to comment on those changes, I'm always interested in feedback.

Thanks,
Dridi

**Comment by Dridi** [comment]
Hi @dbeckham,

I have made up my mind and `rst2man` is now a strong requirement. The RST files are generated along with the VMOD interface and since it makes no sense to cache the latter, I will do the same with the former.

Dridi

**Comment by Dridi** [comment]
Hi @dbeckham,

I changed my mind and actually distribute the manual with releases. So with the *next release*, you should be able to take the distribution tarball and run `configure --with-rst2man=true` and the build will work.

What I mean by dist tarball: the `tar.gz` file attached to this [release](https://github.com/Dridi/libvmod-querystring/releases/tag/v1.0.1) for example.

However this won't work from a `git` checkout, or with the `make` targets that build RPMs or Debs.

I'm reopening this issue until I cut the next release.

Dridi

**Comment by Dridi** [comment]
1.0.2 is out, it should fix this problem. Please yell if it's not the case!

https://github.com/Dridi/libvmod-querystring/releases/latest
