### ISSUE TITLE
Whitelist functionality 

### ISSUE THREAD

**Issue by gsdevme** [Dridi/libvmod-querystring#28]
Hi,

So I've had a little play around with the plugin, is it possible to set a whitelist of query strings? seems I can only do a blacklist? 

For example if I wanted to say to only allow `?v=` on assets it seems a little tricky to do, just as an example.

**Comment by gsdevme** [comment]
Read bits of the C code managed to figure it out, added it to the readme if thats any use https://github.com/Dridi/libvmod-querystring/pull/29

**Comment by Dridi** [comment]
ETIMEDOUT
