### ISSUE TITLE
v1.0.1 doesn't compile at all

### ISSUE THREAD

**Issue by flowl** [Dridi/libvmod-querystring#30]
git clone https://github.com/Dridi/libvmod-querystring.git
    cd libvmod-querystring
    git checkout tags/v1.0.1

Followed the installation steps, doesn't work:

```
root@varnish1:/tmp/libvmod-querystring# ./bootstrap
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build-aux'.
libtoolize: copying file `build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
configure.ac:31: installing 'build-aux/ar-lib'
configure.ac:31: installing 'build-aux/compile'
configure.ac:34: installing 'build-aux/config.guess'
configure.ac:34: installing 'build-aux/config.sub'
configure.ac:29: installing 'build-aux/install-sh'
configure.ac:29: installing 'build-aux/missing'
src/Makefile.am:21: error: CODE_COVERAGE_ENABLED does not appear in AM_CONDITIONAL
src/Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'

root@varnish1:/tmp/libvmod-querystring# make check
make: *** No rule to make target `check'.  Stop.

root@varnish1:/tmp/libvmod-querystring# make
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by Dridi** [comment]
Hello, that would be the steps to build the VMOD from git, do you need to make changes? If not, you should not be using the `bootstrap` script.

**Comment by Dridi** [comment]
OK, I see now that I made changes in the README in the master branch, but you were logically following instructions from the 1.0.1 README. Please try building 1.0.1 following the up-to-date instructions in the master README.

**Comment by flowl** [comment]
Thank you for your reply, glad you help me.
The master branch suggests to use the following:

```
./configure --with-rst2man=:
make check # optional
sudo make install
```

But there is no `configure` file in the source folder.

**Comment by Dridi** [comment]
That is because you are cloning the git repo, please grab the 1.0.1 archive from the release:

https://github.com/Dridi/libvmod-querystring/releases/download/v1.0.1/vmod-querystring-1.0.1.tar.gz

**Comment by flowl** [comment]
Ok, it works now without the manpages option, but I think I would need them (or do you have online docs?).

```
root@varnishd:/tmp/vmod-querystring-1.0.1# make install
Making install in src
make[1]: Entering directory `/tmp/vmod-querystring-1.0.1/src'
  VMODTOOL vmod_querystring.vcc
  CC       vmod_querystring.lo
  CC       vcc_querystring_if.lo
  CCLD     libvmod_querystring.la
: vmod_querystring.man.rst vmod_querystring.3
make[2]: Entering directory `/tmp/vmod-querystring-1.0.1/src'
make[2]: Nothing to be done for `install-exec-am'.
: vmod_querystring.man.rst vmod_querystring.3
 /bin/mkdir -p '/usr/share/man/man3'
 /usr/bin/install -c -m 644 ./vmod_querystring.3 '/usr/share/man/man3'
/usr/bin/install: cannot stat ‘./vmod_querystring.3’: No such file or directory
make[2]: *** [install-man3] Error 1
make[2]: Leaving directory `/tmp/vmod-querystring-1.0.1/src'
make[1]: *** [install-am] Error 2
make[1]: Leaving directory `/tmp/vmod-querystring-1.0.1/src'
make: *** [install-recursive] Error 1
```

**Comment by flowl** [comment]
When I don't use the `--with-rst2man=:` option, it works and the manpage gets installed

    man vmod_querystring 3

Thanks for your assistance.

I would like to suggest to you, to make this repository a little more convenient to use. Proper and fully functional branches and tags, dependency and version constraint quick to spot, usage information online,.. The module itself is really great.

I started some projects on GitHub and I know it's sometimes annoying work to keep it up and maintain all the time, so your help is very appreciated :-)

**Comment by Dridi** [comment]
> When I don't use the `--with-rst2man=:` option, it works and the manpage gets installed

I'm aware of that, it's already fixed in the master branch so it will work for 1.0.2 once I tag it.

> I would like to suggest to you, to make this repository a little more convenient to use.

That's what I tried to do, with release archives having no dependencies on autotools (actuall a feature of the autotools) and requiring them only when building from git. There are a couple more things I want to do before the next release. At this point instructions in the README will match the master branch.

Anyway, glad I could help you and if I break your production, let me know ;)

**Comment by gauthier-delacroix** [comment]
@Dridi I'm facing the same issue (`CODE_COVERAGE_ENABLED does not appear in AM_CONDITIONAL`) building from git.

I've read you asked to build from tgz but I need to build from a puppet module and downloading a tgz is clearly not as clean as pulling a git tag.

What's needed to avoid the `CODE_COVERAGE_ENABLED` error ?
Don't you think your project should be directly usable from git source ?

Thanks!

**Comment by Dridi** [comment]
Hello Gauthier,

When building from git you need to pull additional dependencies, and in your case you are missing the autoconf-archive package.

https://github.com/Dridi/libvmod-querystring#hacking

I would argue that downloading a tgz is as clean as pulling a git tag (with some conditions=). If you look at the github releases since 1.0, I attach the corresponding release tgz as `vmod-querystring-${version}.tar.gz` and those archives don't need the extra dependencies that are needed to build from git. This is the recommended installation.

https://github.com/Dridi/libvmod-querystring#installation

**Comment by Dridi** [comment]
Also, you need Varnish 5.1 to build from git, whereas the release archives work with Varnish >= 4.1.3.

**Comment by gauthier-delacroix** [comment]
Thanks @Dridi,

I'm using 4.1 so I won't insist on this.

Using git would just have been cleaner with Puppet because it handles notifications better from a git repo than from a single file without metadata.

**Comment by Dridi** [comment]
You could technically build from git to target 4.1 but you would need to have both Varnish 4.1 and 5.1 installed. If you don't find that dirty [1], please open a separate issue and I will walk you through the steps.

[1] I wouldn't qualify it as clean :)

**Comment by Dridi** [comment]
Can you have puppet detect git tags and yet download release archives by the way?

**Comment by gauthier-delacroix** [comment]
I won't go that "really not clean" way to keep my puppet code a little cleaner ;o)

Puppet doesn't "detect"' tags. With the tgz, I'll have to forge the file name and check if a file with the same name is already present to know if I have to download it, then forge the URL, and then download and extract it...with Git, I just ask for a tag, and I get the repo to the tag, if not already done.

I get another issue with the archive, I can create a new issue if you prefer:

````
]# make
make  all-recursive
make[1]: Entering directory `/root/vmods/vmod-querystring-1.0.2'
Making all in src
make[2]: Entering directory `/root/vmods/vmod-querystring-1.0.2/src'
  CC       vmod_querystring.lo
gcc: error: unrecognized command line option ‘-Wint-conversion’
make[2]: *** [vmod_querystring.lo] Error 1
make[2]: Leaving directory `/root/vmods/vmod-querystring-1.0.2/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/root/vmods/vmod-querystring-1.0.2'
make: *** [all] Error 2
````

Seems my gcc version is too old, by I'm on CentOS7... which version do you require ?

**Comment by Dridi** [comment]
Please try the opportunistic 1.0.3 archive from #33 and move the discussion there :)
