### ISSUE TITLE
branch 4.0 filter_except generates garbage URL

### ISSUE THREAD

**Issue by flowl** [Dridi/libvmod-querystring#31]
Having the problem like in #25 .

Your branch 4.0 with Varnish 4.1 (other combinations didn't compile).

My varnishd is from the following repo:

    https://repo.varnish-cache.org/debian/ trusty varnish-4.1

    varnishd (varnish-4.1.4 revision 4529ff7)
    Copyright (c) 2006 Verdens Gang AS
    Copyright (c) 2006-2015 Varnish Software AS

It works with some URLs, but with those URLs like the one in this example, they get mixed up the strangest way possible. Even the parameters from the exception list get mixed in several times completely weird (notice 3 times the `?` symbol).
It's not only with long URLs. It happens also with `/article/a.html?some=param`. 

config in recv_pool:

    set req.http.X-Test = querystring.filter_except(req.url,
        "otest"
    );
    set req.http.X-Test = querystring.sort(req.http.X-Test);
    set req.url = querystring.clean(req.http.X-Test);

Requested URL:

    /artikel/aaaaaaaaaa-2017-aa-aaa-aaa-aaaaaaaaaaaa-1234567.html?otest=HELLO

Returned URL:

    /artikel/aa-2017-aaaaaaa-aaaaaaa-html?ot-html?otehtml?otest=HELLest=HELLO

varnishlog output:

    VCL_call       vmod_filter_except("/artikel/aaaaaaaaaa-2017-aa-aaa-aaa-aaaaaaaaaaaa-1234567.html?otest=HELLO", "otest", ...)
    VCL_return     "/artikel/aaaaaaaaaa-2017-aa-aaa-aaa-aaaaaaaaaaaa-1234567.html?otest=HELLO"
    ReqHeader      X-Test: /artikel/aa-2017-aaaaaaa-aaaaaaa-html?ot-html?otehtml?otest=HELLest=HELLO
    VCL_call       vmod_sort("/artikel/aa-2017-aaaaaaa-aaaaaaa-html?ot-html?otehtml?otest=HELLest=HELLO")
    VCL_return     "/artikel/aa-2017-aaaaaaa-aaaaaaa-html?ot-html?otehtml?otest=HELLest=HELLO"
    ReqUnset       X-Test: /artikel/aa-2017-aaaaaaa-aaaaaaa-html?ot-html?otehtml?otest=HELLest=HELLO
    ReqHeader      X-Test: /artikel/aa-2017-aaaaaaa-aaaaaaa-html?ot-html?otehtml?otest=HELLest=HELLO
    VCL_call       vmod_clean("/artikel/aa-2017-aaaaaaa-aaaaaaa-html?ot-html?otehtml?otest=HELLest=HELLO")
    VCL_return     "/artikel/aa-2017-aaaaaaa-aaaaaaa-html?ot-html?otehtml?otest=HELLest=HELLO"
    ReqURL         /artikel/aa-2017-aaaaaaa-aaaaaaa-html?ot-html?otehtml?otest=HELLest=HELLO

**Comment by Dridi** [comment]
I'm not planning further maintenance on the 4.0 branch, so before I look at this I will help you move to the 1.0 series (#30).

**Comment by flowl** [comment]
I read that you rewrote the code regarding the filter(_except) calls,
so if I could use a more recent version of your module, it would be the best solution.

**Comment by Dridi** [comment]
Now that the module builds for you, I'm closing this one.
