### ISSUE TITLE
Varnish 5 support

### ISSUE THREAD

**Issue by blkperl** [Dridi/libvmod-querystring#32]
Is Varnish 5 supported? You have a branch for varnish 4.0 but Varnish 5 does not have one.

**Comment by Dridi** [comment]
Yes, the 4.0 branch is the legacy VMOD, the master branch works with Varnish 4.1.3 and later. Building from git requires at least Varnish 4.1.4, so building for Varnish 5 should not be a problem.

I recommend following the instructions from the README on the current master branch:

https://github.com/Dridi/libvmod-querystring#installation

Let me know if you have trouble building this module or feel free to close this ticket once you're all set.

**Comment by Dridi** [comment]
ETIMEDOUT
