### ISSUE TITLE
Symbol not found: 'querystring.regfilter'

### ISSUE THREAD

**Issue by ProductiveWeb** [Dridi/libvmod-querystring#35]
Hello
i'm trying to migrate to varnish 5.1.3. So i built lib from vmod-querystring-1.0.3.tar.gz release. 

`Symbol not found: 'querystring.regfilter' (expected type STRING_LIST):
('/etc/varnish/default.vcl' Line 89 Pos 45)
set req.http.locale_name = querystring.regfilter(req.http.url, "[^location|locale]");
---------------------------#####################--------------------------------------------`

how can i use the same functionality as in old libvmod version?

**Comment by undead-osiris** [comment]
https://github.com/Dridi/libvmod-querystring/issues/23

**Comment by Dridi** [comment]
Hello @ProductiveWeb,

I somehow forgot about this issue until I started looking at #36 opened recently. In general issues can go unnoticed when they are opened 4 days before a major Varnish release (yes I know, lame excuse :).

Do you still need help or did you manage to upgrade your  code to the new version?

@undead-osiris thanks a lot for stepping in!

**Comment by Dridi** [comment]
ETIMEDOUT
