### ISSUE TITLE
Compile time warnings on el7

### ISSUE THREAD

**Issue by ingvarha** [Dridi/libvmod-querystring#37]
When doing a mock build against varnish-plus-41 on epel7, I get

/usr/include/varnish-plus/miniobj.h:8:5: warning: "HAVE_EXPLICIT_BZERO" is not defined [-Wundef]
 #if HAVE_EXPLICIT_BZERO
     ^
cc1: error: unrecognized command line option "-Wno-int-conversion" [-Werror]
cc1: all warnings being treated as errors

The fix is probably trivial. I can override by removing "-Werror" Red Hat's build CFLAGS.

Also, the generated specfile could have a macro %varnish_name, to make it compatible with both varnish and varnish-plus.

Ingvar

**Comment by Dridi** [comment]
Hello Ingvar!

Regarding `HAVE_EXPLICIT_BZERO`, this is a bug in varnish-plus, I'll fix that. I'll have a closer look at the RPM packaging, thanks for letting me know.

Dridi

**Comment by Dridi** [comment]
All problems are fixed upstream (pending release though) except `-Wno-int-conversion`, it's a problem in vmod-querystring itself. I'm closing this in favor of #36, please subscribe to this issue instead.
