### ISSUE TITLE
src build fails with varnish 6.5.0;  'WS_Reserve()' removed

### ISSUE THREAD

**Issue by pgnd** [Dridi/libvmod-querystring#45]
after upgrading 'varnish'
```
version 6.4.0 -> 6.5.0
```

vmod querystring src rebuild fails at missing 'WE_Reserve' symbol; e.g. @:

	https://download.copr.fedorainfracloud.org/results/pgfed/varnish/fedora-32-x86_64/01678125-vmod-querystring/builder-live.log.gz

```
...
***  v1   debug|Could not delete 'vcl_vcl1.1600526223.737474/vgc.sym': No such file or directory
***  v1   CLI RX  106
**** v1   CLI RX|Message from VCC-compiler:
**** v1   CLI RX|Could not open VMOD querystring
**** v1   CLI RX|\tFile name: /builddir/build/BUILD/vmod-querystring-2.0.1/src/.libs/libvmod_querystring.so
**** v1   CLI RX|\tdlerror: /builddir/build/BUILD/vmod-querystring-2.0.1/src/.libs/libvmod_querystring.so: undefined symbol: WS_Reserve
**** v1   CLI RX|('<vcl.inline>' Line 5 Pos 16)
**** v1   CLI RX|        import querystring;
**** v1   CLI RX|---------------###########-
**** v1   CLI RX|
**** v1   CLI RX|Running VCC-compiler failed, exited with 2
**** v1   CLI RX|VCL compilation failed
...
```

checking notes
```
https://github.com/varnishcache/varnish-cache/blob/master/doc/changes.rst#user-content-next-scheduled-2020-09-15

	"
	...
	Overhaul of the workspace API
		...
		The previously deprecated WS_Reserve() has been removed
		...
	"
```

**Comment by Dridi** [comment]
I'm aware, I made those breaking changes to the workspace API. It turns out this was already fixed in the master branch but I will need to cut a release soon.

This should be fixed in a82c37521f4e6b3d82eae8da79d7616b90ef631c but I would like to do more testing before calling it 2.0.2...

**Comment by Dridi** [comment]
Go grab 2.0.2: https://github.com/Dridi/libvmod-querystring/releases/tag/v2.0.2

**Comment by pgnd** [comment]
@Dridi 

thx! grabbing it now.

when you've a chance, pls bump version at your Fedora COPR repo, for the non-DIY-ers.

**Comment by Dridi** [comment]
I don't maintain a COPR repository for vmod_querystring, but a package exists in the main repositories and was updated for rawhide. Where do you get it from on COPR?

**Comment by pgnd** [comment]
my bad!  not COPR (well, _my_ COPR).  2 many sites! sry.

@ -> https://src.fedoraproject.org/rpms/vmod-querystring.git

i see you just updated that for master.  i can pull & rebuild pkgs in my COPR for F32.  will be eventually useful to bump 'your' F32 builds too, if it doesn't happen automatically ...

**Comment by Dridi** [comment]
That wouldn't solve anything, if I build vmod-querystring 2.0.2 on f32 it would have binary compatibility with Varnish 6.4 and would not load from your custom build of Varnish 6.5 on f32.

**Comment by pgnd** [comment]
ugh. good point!  for now, then i think i should be OK with:

https://copr.fedorainfracloud.org/coprs/pgfed/varnish/packages/

will test here in a bit ...
