### ISSUE TITLE
failed build w/ varnish 6.6: " 'VRT_re_fini' undeclared"

### ISSUE THREAD

**Issue by pgnd** [Dridi/libvmod-querystring#46]
just starting to look at this myself.

fyi, building with varnish 6.6,

https://copr.fedorainfracloud.org/coprs/pgfed/varnish/builds/

build fails @

```
...
make[2]: Leaving directory '/builddir/build/BUILD/vmod-querystring-2.0.2/src'
vmod_querystring.c: In function 'vmod_filter_add_regex':
vmod_querystring.c:598:21: error: 'VRT_re_fini' undeclared (first use in this function); did you mean 'VRT_priv_fini'?
  598 |         qsf->free = VRT_re_fini;
      |                     ^~~~~~~~~~~
      |                     VRT_priv_fini
vmod_querystring.c:598:21: note: each undeclared identifier is reported only once for each function it appears in
```

build log @ 

https://download.copr.fedorainfracloud.org/results/pgfed/varnish/fedora-34-x86_64/02199579-vmod-querystring/builder-live.log.gz

**Comment by Dridi** [comment]
I solved this ahead of time in fffe7583af018e9a9424139d9fc4080586cf3f90 but haven't had time to do a formal release after the Varnish 6.6.0 release. You should be fine adding this commit as a patch in your RPM spec for the time being.

**Comment by pgnd** [comment]
+1

fwiw, a build of HEAD with varnish 6.6, with that^^ commit, builds ok

https://copr.fedorainfracloud.org/coprs/pgfed/varnish/build/2200135/

**Comment by iammeken** [comment]
vmod_querystring.3 missing in /libvmod-querystring/src

have to copy manually :)
