### ISSUE TITLE
src/Makefile.am:26: error: 'vmod_LTLIBRARIES' is used but 'vmoddir' is undefined, varnish 6.6.0

### ISSUE THREAD

**Issue by grupoz** [Dridi/libvmod-querystring#47]
/usr/src/libvmod-querystring# ./bootstrap 
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:30: installing 'build-aux/compile'
configure.ac:29: installing 'build-aux/missing'
src/Makefile.am:26: error: 'vmod_LTLIBRARIES' is used but 'vmoddir' is undefined
automake: warnings are treated as errors
src/Makefile.am:30: warning: variable 'libvmod_querystring_la_SOURCES' is defined but no program or
src/Makefile.am:30: library has 'libvmod_querystring_la' as canonical name (possible typo)
src/Makefile.am:33: warning: variable 'nodist_libvmod_querystring_la_SOURCES' is defined but no program or
src/Makefile.am:33: library has 'libvmod_querystring_la' as canonical name (possible typo)

libvmod-querystring:
https://github.com/Dridi/libvmod-querystring/commit/fffe7583af018e9a9424139d9fc4080586cf3f90
Varnish: 6.6.0
Regards

**Comment by glensc** [comment]
Thanks for the patch! fffe758 fixes the build.

And a reminder to make new release ;)

**Comment by e2-robert** [comment]
Seems to fail again with same error when building upon varnish 7.0.0 with patch from #49:
```
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, `build-aux'.
libtoolize: copying file `build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
libtoolize: copying file `m4/libtool.m4'
libtoolize: copying file `m4/ltoptions.m4'
libtoolize: copying file `m4/ltsugar.m4'
libtoolize: copying file `m4/ltversion.m4'
libtoolize: copying file `m4/lt~obsolete.m4'
configure.ac:30: installing 'build-aux/ar-lib'
configure.ac:33: installing 'build-aux/config.guess'
configure.ac:33: installing 'build-aux/config.sub'
configure.ac:29: installing 'build-aux/install-sh'
configure.ac:29: installing 'build-aux/missing'
src/Makefile.am:26: error: 'vmod_LTLIBRARIES' is used but 'vmoddir' is undefined
parallel-tests: installing 'build-aux/test-driver'
automake: warnings are treated as errors
src/Makefile.am:33: warning: variable 'nodist_libvmod_querystring_la_SOURCES' is defined but no program or
src/Makefile.am:33: library has 'libvmod_querystring_la' as canonical name (possible typo)
src/Makefile.am:30: warning: variable 'libvmod_querystring_la_SOURCES' is defined but no program or
src/Makefile.am:30: library has 'libvmod_querystring_la' as canonical name (possible typo)
```

**Comment by Dridi** [comment]
Is this fixed by the 2.0.3 release?

**Comment by glensc** [comment]
@Dridi yes, if you read the release notes:
- https://github.com/Dridi/libvmod-querystring/releases/tag/v2.0.3

It has:
- "Varnish 6.6 support"

**Comment by e2-robert** [comment]
I failed to build it with Varnish 7.0.

I'm using this Dockerfile (excerpt):
```Dockerfile
FROM centos:7

# TODO: use stable version (non-master) of varnish-cache, modules and pesi
# TODO: clean up build dependencies, since image has got 1G

ENV VARNISH_SIZE 1G

RUN yum install -y python3 python-sphinx

# Install Varnish
# https://github.com/varnishcache/varnish-cache/releases
RUN fetchDeps=' \
        git \
	'; \
	buildDeps=' \
        make \
        autoconf \
        automake \
        libedit-devel \
        libtool \
        libunwind-devel \
        ncurses-devel \
        pcre2-devel \
	'; yum install -y $fetchDeps $buildDeps \
 && git clone --recursive --depth 1 --branch varnish-7.0.0 https://github.com/varnishcache/varnish-cache /usr/src/varnish-cache \
 && cd /usr/src/varnish-cache \
 && sh autogen.sh \
 && sh configure \
 && make \
 && make install \
 && mkdir /etc/varnish \
 && echo -e 'vcl 4.1;\nbackend default none;' > /etc/varnish/default.vcl



# VMOD querystring (https://github.com/Dridi/libvmod-querystring)
# https://github.com/Dridi/libvmod-querystring/releases (#v2.0.3)
ENV VMOD_QUERYSTRING_VERSION 'v2.0.3'
RUN fetchDeps=' \
        git \
    '; \
    buildDeps=' \
        make \
        autoconf \
        automake \
        libtool \
        patch \
        pkgconfig \
        python3-docutils \
    '; yum install -y $fetchDeps $buildDeps \
 && git clone --recursive --depth 1 --branch $VMOD_QUERYSTRING_VERSION https://github.com/Dridi/libvmod-querystring.git /usr/src/libvmod-querystring \
 && cd /usr/src/libvmod-querystring \
 && sh bootstrap \
 && make -j "$(nproc)" \
 && make check \
 && make install \
 && rm -rf /usr/src/libvmod-querystring
```

It fails with the very same error message, namely:
> src/Makefile.am:26: error: 'vmod_LTLIBRARIES' is used but 'vmoddir' is undefined

**Comment by Dridi** [comment]
@e2-robert the answers were in the README.

You aren't installing Varnish in the `/usr` prefix so you need to tell pkg-config about that. For reasons that escape me you are cloning the git repositories instead of downloading already-bootstrapped release archives so you also need to bootstrap it. Again, you need to tell aclocal about the non-`/usr` prefix where Varnish was installed. The bootstrap script enables warnings and one of them is triggering with gcc on el7 so you need to disable them.

```diff
@@ -36,6 +36,8 @@
 # VMOD querystring (https://github.com/Dridi/libvmod-querystring)
 # https://github.com/Dridi/libvmod-querystring/releases (#v2.0.3)
 ENV VMOD_QUERYSTRING_VERSION 'v2.0.3'
+ENV ACLOCAL_PATH=/usr/local/share/aclocal
+ENV PKG_CONFIG_PATH=/usr/local/lib/pkgconfig
 RUN fetchDeps=' \
         git \
     '; \
@@ -50,7 +52,7 @@
     '; yum install -y $fetchDeps $buildDeps \
  && git clone --recursive --depth 1 --branch $VMOD_QUERYSTRING_VERSION https://github.com/Dridi/libvmod-querystring.git /usr/src/libvmod-querystring \
  && cd /usr/src/libvmod-querystring \
- && sh bootstrap \
+ && sh bootstrap --disable-warnings \
  && make -j "$(nproc)" \
  && make check \
  && make install \
```
