### ISSUE TITLE
Keep order within array/duplicate parameters

### ISSUE THREAD

**Issue by pgrunewald** [dridi/libvmod-querystring#53]
There are some systems, that rely on the order of so called array parameters.

Like in PHP:

> ?steps[]=ZZZ&steps[]=AAA

Or Zope-based applications:

> ?steps:list=ZZZ&steps:list=AAA

What querystring currently does, is to sort those keys also by its value. So the results would be:

> ?steps[]=AAA&steps[]=ZZZ

and

> ?steps:list=AAA&steps:list=ZZZ

The application receives then a different order. Is there a way to keep the order of those parameters?

**Comment by dridi** [comment]
You can already do this today:

```vcl
sub vcl_init {
        new name_sort = querystring.filter(sort = true, match = name);
}

sub vcl_recv {
        set req.url = name_sort.apply();
}
```

The `querystring.sort()` shorthand sorts full parameters as you noted, but this is the documented behavior:

> This is a shorthand function that works like applying a sorting-enabled filter with no criteria matching full parameters, not just  their  names.

Does that solve your problem?

**Comment by pgrunewald** [comment]
Superb. That does indeed work. Thank you! Closing this issue now.
